[phases.setup]
nixPkgs=['...', 'python39', 'gccStdenv', 'cairo']
aptPkgs=['build-essential', 'libcairo2-dev', 'libpango1.0-dev', 'libjpeg-dev', 'libgif-dev', 'librsvg2-dev']

[phases.install]
cmds=['npm ci']

[phases.build]
cmds=['npm run build']

[start]
cmd='npm run start'